# Generated by Django 5.1.1 on 2024-11-24 22:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_solicitudtarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtarea',
            name='fecha_finalizacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='solicitudtarea',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='solicitudtarea',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudtarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitudtarea',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
