# Generated by Django 5.1.1 on 2024-12-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoempresarial',
            name='nombre',
            field=models.CharField(default='Proceso sin nombre', max_length=150),
        ),
    ]
