# Generated by Django 5.1.5 on 2025-02-07 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_procesoempresarial_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoempresarial',
            name='firmado_por',
            field=models.ManyToManyField(blank=True, related_name='firmas_procesos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procesoempresarial',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
