# Generated by Django 5.1.5 on 2025-02-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_procesoempresarial_firmado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='dia',
            field=models.CharField(choices=[('todos', 'Todos los días'), ('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sábado', 'Sábado')], default='todos', max_length=10),
        ),
    ]
