# Generated by Django 5.1.5 on 2025-02-09 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_notificacion_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_puesto', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puestos', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='core.sector')),
            ],
        ),
        migrations.AddField(
            model_name='procesoempresarial',
            name='perfiles',
            field=models.ManyToManyField(blank=True, related_name='procesos', to='core.perfilpuesto'),
        ),
    ]
