# Generated by Django 5.1.5 on 2025-02-10 01:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_perfilpuesto_procesoempresarial_perfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesoempresarial',
            name='perfiles',
        ),
        migrations.AddField(
            model_name='procesoempresarial',
            name='perfiles_puesto',
            field=models.ManyToManyField(blank=True, related_name='procesos_asociados', to='core.perfilpuesto'),
        ),
        migrations.AddField(
            model_name='procesoempresarial',
            name='usuarios_del_sector',
            field=models.ManyToManyField(blank=True, related_name='procesos_asociados', to=settings.AUTH_USER_MODEL),
        ),
    ]
