# Generated by Django 5.1.5 on 2025-02-10 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_procesoempresarial_perfiles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructivoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_sector', models.TextField(blank=True)),
                ('sector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructivo_general', to='core.sector')),
            ],
        ),
    ]
