# Generated by Django 5.1.5 on 2025-02-11 17:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_procesoempresarial_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procesoempresarial',
            old_name='descripcion_sector',
            new_name='alcance',
        ),
        migrations.RenameField(
            model_name='procesoempresarial',
            old_name='insumos',
            new_name='equipo_requerido',
        ),
        migrations.RemoveField(
            model_name='procesoempresarial',
            name='aceptado_por',
        ),
        migrations.RemoveField(
            model_name='procesoempresarial',
            name='cuit',
        ),
        migrations.RemoveField(
            model_name='procesoempresarial',
            name='email',
        ),
        migrations.RemoveField(
            model_name='procesoempresarial',
            name='firmado_por',
        ),
        migrations.RemoveField(
            model_name='procesoempresarial',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='procesoempresarial',
            name='perfiles_puesto',
        ),
        migrations.RemoveField(
            model_name='procesoempresarial',
            name='tareas',
        ),
        migrations.RemoveField(
            model_name='procesoempresarial',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='procesoempresarial',
            name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='procesoempresarial',
            name='usuarios_del_sector',
        ),
        migrations.AddField(
            model_name='procesoempresarial',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='procesoempresarial',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='procesoempresarial',
            name='medidas_seguridad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procesoempresarial',
            name='objetivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procesoempresarial',
            name='pasos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procesoempresarial',
            name='responsabilidades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procesoempresarial',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='procesoempresarial',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_empresariales', to='core.sector'),
        ),
        migrations.CreateModel(
            name='InstructivoCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('fecha_revision', models.DateField(auto_now=True)),
                ('objetivo', models.TextField()),
                ('alcance', models.TextField()),
                ('responsabilidades', models.TextField()),
                ('pasos', models.TextField()),
                ('criterios_evaluacion', models.TextField()),
                ('normativa_asociada', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructivos_calidad_creados', to=settings.AUTH_USER_MODEL)),
                ('firmado_por', models.ManyToManyField(blank=True, related_name='firmas_instructivos_calidad', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructivos_calidad', to='core.sector')),
            ],
            options={
                'verbose_name': 'Instructivo de Calidad',
                'verbose_name_plural': 'Instructivos de Calidad',
            },
        ),
        migrations.CreateModel(
            name='InstructivoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('fecha_revision', models.DateField(auto_now=True)),
                ('objetivo', models.TextField()),
                ('alcance', models.TextField()),
                ('responsabilidades', models.TextField()),
                ('pasos', models.TextField()),
                ('equipo_requerido', models.TextField(blank=True, null=True)),
                ('medidas_seguridad', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructivos_trabajo_creados', to=settings.AUTH_USER_MODEL)),
                ('firmado_por', models.ManyToManyField(blank=True, related_name='firmas_instructivos_trabajo', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructivos_trabajo', to='core.sector')),
            ],
            options={
                'verbose_name': 'Instructivo de Trabajo',
                'verbose_name_plural': 'Instructivos de Trabajo',
            },
        ),
    ]
