# Generated by Django 5.1.5 on 2025-02-15 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_instructivocalidad_logo_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructivogeneral',
            name='firmado_por',
            field=models.ManyToManyField(blank=True, related_name='firmas_instructivos', to=settings.AUTH_USER_MODEL),
        ),
    ]
