# Generated by Django 5.1.5 on 2025-02-15 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_instructivogeneral_firmado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructivogeneral',
            name='firmado_por',
            field=models.ManyToManyField(blank=True, related_name='firmas_instructivos_generales', to=settings.AUTH_USER_MODEL),
        ),
    ]
