# Generated by Django 5.1.5 on 2025-02-19 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_instructivogeneral_firmado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=10),
        ),
        migrations.AddField(
            model_name='tarea',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tiempo_dedicado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Curso', 'En Curso'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='notificacion',
            field=models.CharField(choices=[('Programadas', 'Programadas'), ('Automaticas', 'Automaticas')], default='Programadas', max_length=20),
        ),
    ]
