# Generated by Django 5.1.5 on 2025-02-20 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_tarea_prioridad_tarea_responsable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlujoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='FlujoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sector')),
                ('tareas', models.ManyToManyField(through='core.FlujoTarea', to='core.tarea')),
            ],
        ),
        migrations.AddField(
            model_name='flujotarea',
            name='flujo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.flujotrabajo'),
        ),
    ]
