# Generated by Django 5.1.5 on 2025-02-25 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_flujotarea_flujotrabajo_flujotarea_flujo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujotarea',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
